language: ruby
before_install: gem install bundler
install: bundle install
script: rake
rvm:
- 1.9.3
- 2.0.0
- 2.1.1
- 2.2.0
notifications:
  slack:
    secure: tsYjJ2lHbYChbhHCFqY8SuJ85ZKtjho7hPO2ezghCqOmn2b/wNM60jo47VX8dLmDz9h1t/BcO3eeiaE4YC3E1bAdq/VaC481ZCcsCH61TVXCFmIDgJTLGutRWYDc2jH4/URpaZztDTz6DHt3dmvHzsle3snUj4OahLA9nLGkOTmqG+/VVf0/rSx/VjG6AMItYHQpHozdDZaTNdCmpW6kvhkSMvr7MlKmjfgdSCN5oYcbqvVYErFU8e8Ve4muMJ1KXSUp7VTx/X4ECTaqTIQQL5F1eNH9nWz3ftzipd/0EDgJTVWljpzyHpRZU/RgFgHole/5Xl0eMGInDhzUaRgz5hl6AU21GRNxMsCwytc/lUS1i/91JEyXfTqJpmbhsa8k4bSyQGJ5546b0+CET1JsSiD4b6KIO/l3AEOjC/aPFXkxtFQBYS33OJW/LB6rhyiDvRECSvGmliIsZshVaG1Wv+hJQKg24ZWI5bnSTgf/ZPcBjawqLVEaUByeSMV5LlX3/BKEHopgv049E5z05ptcAsG/iA7I26PQvHXDuTI+PclWgONgW15Cfi4kuXtFC8NET2hdIxvrNVD3YMnwZehtS5cFcWFu4Aa3uYETNKNFjTOkuP/zE6erJD/0qTSGE/cr2rJUYZyJeBcm70/BZL1qFJ3MGM+f03IiTDdavFdPej8=
